version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: omar
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: mariachisdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./Backend-MariachisTexas
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://omar:123456@postgres:5432/mariachisdb
      JWT_SECRET: tu_secret
      PORT: 3000
    depends_on:
      - postgres

  frontend:
    build: ./Frontend-MariachisTexas
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata: